name: conda_growspace
channels:
  - pytorch
  - anaconda
  - powerai
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numba
  - gym
  - opencv
  - tqdm
  - torchvision
  - pip:
    - scipy
    - scikit-learn