name: conda_growspace
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numba
  - numpy
  - matplotlib
  - gym
  - opencv
  - tqdm
  - torchvision
  - stable-baselines3
  - pip:
    - scipy
    - scikit-learn